"""Data parsing for BPMN 2.0 XML bpmn."""

from typing import Any

IMPORT_ORDER = [
    "pybpmn_parser.bpmn.dc.point.Point",
    "pybpmn_parser.bpmn.dc.font.Font",
    "pybpmn_parser.bpmn.dc.bounds.Bounds",
    "pybpmn_parser.bpmn.foundation.documentation.Documentation",
    "pybpmn_parser.bpmn.foundation.extension.Extension",
    "pybpmn_parser.bpmn.foundation.extension_elements.ExtensionElements",
    "pybpmn_parser.bpmn.foundation.base_element.BaseElement",
    "pybpmn_parser.bpmn.foundation.base_element.RootElement",
    "pybpmn_parser.bpmn.data.io_binding.IoBinding",
    "pybpmn_parser.bpmn.infrastructure.import_mod.Import",
    "pybpmn_parser.bpmn.di.diagram_element.DiagramElement",
    "pybpmn_parser.bpmn.di.node.Node",
    "pybpmn_parser.bpmn.di.edge.Waypoint",
    "pybpmn_parser.bpmn.di.edge.Edge",
    "pybpmn_parser.bpmn.di.diagram.Diagram",
    "pybpmn_parser.bpmn.service.operation.Operation",
    "pybpmn_parser.bpmn.process.auditing.Auditing",
    "pybpmn_parser.bpmn.process.monitoring.Monitoring",
    "pybpmn_parser.bpmn.process.lane.Lane",
    "pybpmn_parser.bpmn.process.lane.LaneSet",
    "pybpmn_parser.bpmn.activities.rendering.Rendering",
    "pybpmn_parser.bpmn.types.RelationshipDirection",
    "pybpmn_parser.bpmn.foundation.relationship.Relationship",
    "pybpmn_parser.bpmn.data.data_state.DataState",
    "pybpmn_parser.bpmn.data.input_set.InputSet",
    "pybpmn_parser.bpmn.data.output_set.OutputSet",
    "pybpmn_parser.bpmn.conversation.conversation_link.ConversationLink",
    "pybpmn_parser.bpmn.conversation.conversation_association.ConversationAssociation",
    "pybpmn_parser.bpmn.common.correlation_key.CorrelationKey",
    "pybpmn_parser.bpmn.common.expression.Expression",
    "pybpmn_parser.bpmn.common.expression.FormalExpression",
    "pybpmn_parser.bpmn.common.resource_parameter.ResourceParameter",
    "pybpmn_parser.bpmn.collaboration.message_flow.MessageFlow",
    "pybpmn_parser.bpmn.collaboration.message_flow_association.MessageFlowAssociation",
    "pybpmn_parser.bpmn.collaboration.participant_association.ParticipantAssociation",
    "pybpmn_parser.bpmn.collaboration.participant_multiplicity.ParticipantMultiplicity",
    "pybpmn_parser.bpmn.common.artifact.Artifact",
    "pybpmn_parser.bpmn.common.category.CategoryValue",
    "pybpmn_parser.bpmn.common.category.Category",
    "pybpmn_parser.bpmn.data.data_input.DataInput",
    "pybpmn_parser.bpmn.data.data_object.DataObject",
    "pybpmn_parser.bpmn.data.data_output.DataOutput",
    "pybpmn_parser.bpmn.event_definition.event_definition.EventDefinition",
    "pybpmn_parser.bpmn.event_definition.cancel_event_definition.CancelEventDefinition",
    "pybpmn_parser.bpmn.event_definition.compensate_event_definition.CompensateEventDefinition",
    "pybpmn_parser.bpmn.event_definition.conditional_event_definition.ConditionalEventDefinition",
    "pybpmn_parser.bpmn.event_definition.error_event_definition.ErrorEventDefinition",
    "pybpmn_parser.bpmn.event_definition.escalation_event_definition.EscalationEventDefinition",
    "pybpmn_parser.bpmn.event_definition.link_event_definition.LinkEventDefinition",
    "pybpmn_parser.bpmn.event_definition.message_event_definition.MessageEventDefinition",
    "pybpmn_parser.bpmn.event_definition.signal_event_definition.SignalEventDefinition",
    "pybpmn_parser.bpmn.event_definition.terminate_event_definition.TerminateEventDefinition",
    "pybpmn_parser.bpmn.event_definition.timer_event_definition.TimerEventDefinition",
    "pybpmn_parser.bpmn.data.property.Property",
    "pybpmn_parser.bpmn.data.data_store.DataStore",
    "pybpmn_parser.bpmn.data.data_store_reference.DataStoreReference",
    "pybpmn_parser.bpmn.data.data_object_reference.DataObjectReference",
    "pybpmn_parser.bpmn.data.assignment.Assignment",
    "pybpmn_parser.bpmn.data.data_association.DataAssociation",
    "pybpmn_parser.bpmn.data.data_association.DataInputAssociation",
    "pybpmn_parser.bpmn.data.data_association.DataOutputAssociation",
    "pybpmn_parser.bpmn.event.escalation.Escalation",
    "pybpmn_parser.bpmn.event.signal.Signal",
    "pybpmn_parser.bpmn.event.Event",
    "pybpmn_parser.bpmn.event.throw_event.ThrowEvent",
    "pybpmn_parser.bpmn.event.catch_event.CatchEvent",
    "pybpmn_parser.bpmn.event.intermediate_throw_event.IntermediateThrowEvent",
    "pybpmn_parser.bpmn.event.end_event.EndEvent",
    "pybpmn_parser.bpmn.event.intermediate_catch_event.IntermediateCatchEvent",
    "pybpmn_parser.bpmn.event.start_event.StartEvent",
    "pybpmn_parser.bpmn.event.boundary_event.BoundaryEvent",
    "pybpmn_parser.bpmn.event.implicit_throw_event.ImplicitThrowEvent",
    "pybpmn_parser.bpmn.activities.complex_behavior_definition.ComplexBehaviorDefinition",
    "pybpmn_parser.bpmn.activities.loop_characteristics.LoopCharacteristics",
    "pybpmn_parser.bpmn.activities.loop_characteristics.MultiInstanceLoopCharacteristics",
    "pybpmn_parser.bpmn.activities.loop_characteristics.StandardLoopCharacteristics",
    "pybpmn_parser.bpmn.di.shape.Shape",
    "pybpmn_parser.bpmn.di.plane.Plane",
    "pybpmn_parser.bpmn.di.label.Label",
    "pybpmn_parser.bpmn.common.flow_element.FlowElement",
    "pybpmn_parser.bpmn.service.interface.Interface",
    "pybpmn_parser.bpmn.service.end_point.EndPoint",
    "pybpmn_parser.bpmn.collaboration.participant.Participant",
    "pybpmn_parser.bpmn.collaboration.participant.PartnerEntity",
    "pybpmn_parser.bpmn.collaboration.participant.PartnerRole",
    "pybpmn_parser.bpmn.common.error.Error",
    "pybpmn_parser.bpmn.common.message.Message",
    "pybpmn_parser.bpmn.common.item_definition.ItemDefinition",
    "pybpmn_parser.bpmn.conversation.conversation_node.ConversationNode",
    "pybpmn_parser.bpmn.common.resource_parameter_binding.ResourceParameterBinding",
    "pybpmn_parser.bpmn.activities.resource_assignment_expression.ResourceAssignmentExpression",
    "pybpmn_parser.bpmn.common.resource.Resource",
    "pybpmn_parser.bpmn.common.text_annotation.TextAnnotation",
    "pybpmn_parser.bpmn.common.group.Group",
    "pybpmn_parser.bpmn.common.association.Association",
    "pybpmn_parser.bpmn.bpmndi.bpmnlabel.BPMNLabel",
    "pybpmn_parser.bpmn.bpmndi.types.ParticipantBandKind",
    "pybpmn_parser.bpmn.bpmndi.types.MessageVisibleKind",
    "pybpmn_parser.bpmn.bpmndi.bpmnshape.BPMNShape",
    "pybpmn_parser.bpmn.bpmndi.bpmnedge.BPMNEdge",
    "pybpmn_parser.bpmn.bpmndi.bpmnplane.BPMNPlane",
    "pybpmn_parser.bpmn.bpmndi.bpmnlabel_style.BPMNLabelStyle",
    "pybpmn_parser.bpmn.di.labeled_edge.LabeledEdge",
    "pybpmn_parser.bpmn.di.labeled_shape.LabeledShape",
    "pybpmn_parser.bpmn.common.sequence_flow.SequenceFlow",
    "pybpmn_parser.bpmn.common.flow_node.FlowNode",
    "pybpmn_parser.bpmn.conversation.call_conversation.CallConversation",
    "pybpmn_parser.bpmn.conversation.conversation.Conversation",
    "pybpmn_parser.bpmn.conversation.sub_conversation.SubConversation",
    "pybpmn_parser.bpmn.common.correlation_property_retrieval_expression.CorrelationPropertyRetrievalExpression",
    "pybpmn_parser.bpmn.common.correlation_property_binding.CorrelationPropertyBinding",
    "pybpmn_parser.bpmn.activities.resource_role.ResourceRole",
    "pybpmn_parser.bpmn.collaboration.collaboration.Collaboration",
    "pybpmn_parser.bpmn.bpmndi.bpmndiagram.BPMNDiagram",
    "pybpmn_parser.bpmn.gateway.Gateway",
    # "pybpmn_parser.bpmn.choreography.choreography_activity.ChoreographyActivity",
    "pybpmn_parser.bpmn.data.io_specification.IoSpecification",
    "pybpmn_parser.bpmn.common.correlation_property.CorrelationProperty",
    "pybpmn_parser.bpmn.common.correlation_subscription.CorrelationSubscription",
    "pybpmn_parser.bpmn.process.performer.HumanPerformer",
    "pybpmn_parser.bpmn.process.performer.Performer",
    "pybpmn_parser.bpmn.process.performer.PotentialOwner",
    "pybpmn_parser.bpmn.conversation.global_conversation.GlobalConversation",
    "pybpmn_parser.bpmn.gateway.complex_gateway.ComplexGateway",
    "pybpmn_parser.bpmn.gateway.event_based_gateway.EventBasedGateway",
    "pybpmn_parser.bpmn.gateway.exclusive_gateway.ExclusiveGateway",
    "pybpmn_parser.bpmn.gateway.inclusive_gateway.InclusiveGateway",
    "pybpmn_parser.bpmn.gateway.parallel_gateway.ParallelGateway",
    # "pybpmn_parser.bpmn.choreography.call_choreography.CallChoreography",
    # "pybpmn_parser.bpmn.choreography.choreography_task.ChoreographyTask",
    "pybpmn_parser.bpmn.common.callable_element.CallableElement",
    "pybpmn_parser.bpmn.activities.activity.Activity",
    "pybpmn_parser.bpmn.activities.user_task.UserTask",
    "pybpmn_parser.bpmn.activities.manual_task.ManualTask",
    "pybpmn_parser.bpmn.activities.service_task.ServiceTask",
    "pybpmn_parser.bpmn.activities.send_task.SendTask",
    "pybpmn_parser.bpmn.activities.receive_task.ReceiveTask",
    "pybpmn_parser.bpmn.activities.script_task.ScriptTask",
    "pybpmn_parser.bpmn.activities.business_rule_task.BusinessRuleTask",
    "pybpmn_parser.bpmn.activities.call_activity.CallActivity",
    "pybpmn_parser.bpmn.activities.task.Task",
    # "pybpmn_parser.bpmn.choreography.sub_choreography.SubChoreography",
    # "pybpmn_parser.bpmn.choreography.choreography.Choreography",
    "pybpmn_parser.bpmn.activities.sub_process.AdHocSubProcess",
    "pybpmn_parser.bpmn.activities.sub_process.Transaction",
    "pybpmn_parser.bpmn.process.global_task.GlobalTask",
    "pybpmn_parser.bpmn.process.process.Process",
    "pybpmn_parser.bpmn.activities.sub_process.SubProcess",
    # "pybpmn_parser.bpmn.choreography.global_choreography_task.GlobalChoreographyTask",
    "pybpmn_parser.bpmn.activities.global_manual_task.GlobalManualTask",
    "pybpmn_parser.bpmn.activities.global_user_task.GlobalUserTask",
    "pybpmn_parser.bpmn.activities.global_script_task.GlobalScriptTask",
    "pybpmn_parser.bpmn.activities.global_business_rule_task.GlobalBusinessRuleTask",
    "pybpmn_parser.bpmn.infrastructure.definitions.Definitions",
]


def load_classes() -> None:
    """Load all classes in the module."""
    import importlib

    for module_path in IMPORT_ORDER:
        module_name, class_name = module_path.rsplit(".", 1)
        mod = importlib.import_module(module_name)
        globals().update({class_name: getattr(mod, class_name)})


def get_loaded_namespace() -> dict[str, Any]:
    """Get a list of all loaded classes in the module."""
    return globals()


load_classes()
